# Generated by Django 4.2.11 on 2026-06-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('categoria', models.CharField(choices=[('CPU', 'CPU'), ('GPU', 'GPU'), ('RAM', 'RAM'), ('Storage', 'Storage'), ('PSU', 'PSU'), ('Motherboard', 'Motherboard'), ('Cooler', 'Cooler'), ('Case', 'Case')], max_length=30, verbose_name='Categoría')),
                ('especificacion', models.TextField(verbose_name='Especificación')),
                ('gama', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10, verbose_name='Gama')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
                'ordering': ['-created_at'],
            },
        ),
    ]
